


// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DBConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=LAPTOP-V3HVBGB5;Initial Catalog=Work_Flow;Integrated Security=true`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dapper.DAL.Models
{
    /// <summary>
    /// A class which represents the Vill_Profile table.
    /// </summary>
    [Table("Vill_Profile")]
    public partial class Vill_Profile
    {
        [Key]
    	[Required] 
	    public virtual int Vill_ID { get; set; }
        public virtual string CONTITUENCY { get; set; }
        public virtual string District { get; set; }
        public virtual string BLOCK { get; set; }
        public virtual string VILLAGE { get; set; }
        public virtual string Total_votes { get; set; }
        public virtual string Caste_Major { get; set; }
        public virtual string Previous_prob { get; set; }
        public virtual string Remarks { get; set; }
        public virtual string comments { get; set; }
        public virtual string Sarpanch_name { get; set; }
        public virtual string Sarpanch_mobile { get; set; }
        public virtual string permanent_address1 { get; set; }
        public virtual string caste { get; set; }
        public virtual string Father_Husband_Name { get; set; }
        public virtual string gender { get; set; }
        public virtual string education { get; set; }
        public virtual string occupation { get; set; }
        public virtual string dob { get; set; }
        public virtual int? approx_age { get; set; }
        public virtual string marital_status_id { get; set; }
        public virtual string email_id { get; set; }
        public virtual string adhar_no { get; set; }
        public virtual string cor_address1 { get; set; }

    }

    /// <summary>
    /// A class which represents the tbVillageProfile table.
    /// </summary>
    [Table("tbVillageProfile")]
    public partial class tbVillageProfile
    {
        [Key]
    	[Required] 
	    public virtual int profileID { get; set; }
        public virtual string contituency { get; set; }
        public virtual string district { get; set; }
        public virtual string block { get; set; }
        public virtual string village { get; set; }
        public virtual string totalVotes { get; set; }
        public virtual string casteMajor { get; set; }
        public virtual string problems { get; set; }
        public virtual string remarks { get; set; }
        public virtual string comments { get; set; }
        public virtual int? sarpanchID { get; set; }

    }

    /// <summary>
    /// A class which represents the Role_Master table.
    /// </summary>
    [Table("Role_Master")]
    public partial class Role_Master
    {
        public virtual int? Role_Id { get; set; }
        public virtual string Description { get; set; }

    }

    /// <summary>
    /// A class which represents the Teams table.
    /// </summary>
    [Table("Teams")]
    public partial class Teams
    {
        [Key]
    	[Required] 
	    public virtual int Team_id { get; set; }
        public virtual int? Activity_id { get; set; }
        public virtual string role { get; set; }
        public virtual string Team_Name { get; set; }
        public virtual string Remarks { get; set; }

    }

    /// <summary>
    /// A class which represents the Activity table.
    /// </summary>
    [Table("Activity")]
    public partial class Activity
    {
        [Key]
    	[Required] 
	    public virtual int ID_ACTIVITY { get; set; }
        public virtual string Constituency { get; set; }
        public virtual string Area_Type { get; set; }
        public virtual string Village { get; set; }
        public virtual string Booth { get; set; }
        public virtual string Work_Type { get; set; }
        public virtual string name { get; set; }
        public virtual string role { get; set; }
        public virtual DateTime? date { get; set; }
        public virtual string Remarks { get; set; }
        public virtual string Booth_Number { get; set; }
        public virtual string Volunteer_Name { get; set; }
        public virtual string Volunteer_mobile { get; set; }
        public virtual string volunteer_address { get; set; }

    }

    /// <summary>
    /// A class which represents the CONSTITUENCY table.
    /// </summary>
    [Table("CONSTITUENCY")]
    public partial class CONSTITUENCY
    {
        public virtual int? CON_ID { get; set; }
        public virtual string _CONSTITUENCY { get; set; }

    }

    /// <summary>
    /// A class which represents the User_Login table.
    /// </summary>
    [Table("User_Login")]
    public partial class User_Login
    {
        [Key]
    	[Required] 
	    public virtual int UserId { get; set; }
        public virtual string User_Name { get; set; }
        public virtual string Password { get; set; }
        public virtual string Team_Name { get; set; }
        public virtual string role { get; set; }
        public virtual int? Task_id { get; set; }

    }

    /// <summary>
    /// A class which represents the Tasks table.
    /// </summary>
    [Table("Tasks")]
    public partial class Tasks
    {
        [Key]
    	[Required] 
	    public virtual int Task_ID { get; set; }
        public virtual int? Team_ID { get; set; }
        public virtual int? Activity_ID { get; set; }
        public virtual string Task_Description { get; set; }
        public virtual string Deadline_Start { get; set; }
        public virtual string Deadline_End { get; set; }
        public virtual string Role { get; set; }
        public virtual string Remarks { get; set; }
        public virtual string Status { get; set; }
        public virtual string Team_Remarks { get; set; }
        public virtual string Priority { get; set; }
        public virtual DateTime? Start_Time { get; set; }
        public virtual DateTime? end_time { get; set; }

    }

    /// <summary>
    /// A class which represents the Team_Member table.
    /// </summary>
    [Table("Team_Member")]
    public partial class Team_Member
    {
        [Key]
    	[Required] 
	    public virtual int Id_Member { get; set; }
        public virtual string Member_Name { get; set; }
        public virtual string Team_Name { get; set; }

    }

    /// <summary>
    /// A class which represents the Sub_Task2 table.
    /// </summary>
    [Table("Sub_Task2")]
    public partial class Sub_Task2
    {
        [Key]
    	[Required] 
	    public virtual int Sub_Task_id { get; set; }
        public virtual string sub_Desc { get; set; }
        public virtual int? Assigned_member { get; set; }
        public virtual int? Task_ID { get; set; }
        public virtual string Status { get; set; }
        public virtual string Member_Remarks { get; set; }

    }

    /// <summary>
    /// A class which represents the Act_Flow_Team table.
    /// </summary>
    [Table("Act_Flow_Team")]
    public partial class Act_Flow_Team
    {
        [Key]
    	[Required] 
	    public virtual int Team_ID { get; set; }
        public virtual string Team_Name { get; set; }
        public virtual int? Activity_ID { get; set; }

    }

    /// <summary>
    /// A class which represents the Flow_Activity table.
    /// </summary>
    [Table("Flow_Activity")]
    public partial class Flow_Activity
    {
        [Key]
    	[Required] 
	    public virtual int Activity_id { get; set; }
        public virtual string Activity_Name { get; set; }

    }

    /// <summary>
    /// A class which represents the Flow_Activity_Member table.
    /// </summary>
    [Table("Flow_Activity_Member")]
    public partial class Flow_Activity_Member
    {
        [Key]
    	[Required] 
	    public virtual int mem_id { get; set; }
        public virtual string member_name { get; set; }
        public virtual int? Team_ID { get; set; }

    }

    /// <summary>
    /// A class which represents the Work_Allotment table.
    /// </summary>
    [Table("Work_Allotment")]
    public partial class Work_Allotment
    {
        [Key]
    	[Required] 
	    public virtual int Task_ID { get; set; }
        public virtual string Task_Desc { get; set; }
        public virtual int? member_id { get; set; }
        public virtual int? Team_ID { get; set; }
        public virtual DateTime? End_date { get; set; }
        public virtual DateTime? Start_date { get; set; }
        public virtual string Instruction { get; set; }
        public virtual string Status { get; set; }
        public virtual string Link { get; set; }
        public virtual string Member_remarks { get; set; }
        public virtual string Priority { get; set; }
        public virtual string doc_link { get; set; }

    }

    /// <summary>
    /// A class which represents the VILLAGE_MASTER table.
    /// </summary>
    [Table("VILLAGE_MASTER")]
    public partial class VILLAGE_MASTER
    {
        [Key]
    	[Required] 
	    public virtual int VILLAGE_ID { get; set; }
        public virtual int? CONSTITUENCY_ID { get; set; }
        public virtual string VILLAGE_NAME { get; set; }

    }

    /// <summary>
    /// A class which represents the VILL_CASTE table.
    /// </summary>
    [Table("VILL_CASTE")]
    public partial class VILL_CASTE
    {
        [Key]
    	[Required] 
	    public virtual int caste_id { get; set; }
        public virtual string caste_name { get; set; }
        public virtual string caste_population { get; set; }
        public virtual int? vill_id { get; set; }

    }

    /// <summary>
    /// A class which represents the Panch table.
    /// </summary>
    [Table("Panch")]
    public partial class Panch
    {
        public virtual string District { get; set; }
        public virtual string Block { get; set; }
        public virtual string Panchayat { get; set; }
        public virtual string Ward { get; set; }
        public virtual string Name { get; set; }
        public virtual string Father_Husband_Name { get; set; }
        public virtual string Mobile { get; set; }
        public virtual string permanent_address1 { get; set; }
        public virtual string casteresource { get; set; }
        public virtual string genderresource { get; set; }
        public virtual string education { get; set; }
        public virtual string occupationaresource { get; set; }
        public virtual DateTime? dob { get; set; }
        public virtual string approx_age { get; set; }
        public virtual string marital_status { get; set; }
        public virtual string cor_address1 { get; set; }
        public virtual string cor_address2 { get; set; }
        public virtual string cor_address3 { get; set; }
        public virtual string permanent_address11 { get; set; }
        public virtual string permanent_address2 { get; set; }
        public virtual string permanent_address3 { get; set; }
        public virtual string email_id { get; set; }
        public virtual string adhar_no { get; set; }
    	[Required] 
	    public virtual int ID { get; set; }

    }

    /// <summary>
    /// A class which represents the constituency_master table.
    /// </summary>
    [Table("constituency_master")]
    public partial class constituency_master
    {
        public virtual int? ID { get; set; }
        public virtual string CONSTITUENCY { get; set; }
        public virtual string DISTRICT { get; set; }

    }

    /// <summary>
    /// A class which represents the internship table.
    /// </summary>
    [Table("internship")]
    public partial class internship
    {
        [Key]
    	[Required] 
	    public virtual int inter_id { get; set; }
        public virtual DateTime? DATE { get; set; }
        public virtual string name { get; set; }
        public virtual string email { get; set; }
        public virtual string mobile { get; set; }
        public virtual string graduation_degree { get; set; }
        public virtual string graduation_college { get; set; }
        public virtual string post_graduation_college { get; set; }
        public virtual string post_graduation_degree { get; set; }
        public virtual string last_org { get; set; }
        public virtual string current_loc { get; set; }
        public virtual string experience { get; set; }
        public virtual string facebook_profile { get; set; }
        public virtual string join_purpose { get; set; }

    }

    /// <summary>
    /// A class which represents the Sarpanch table.
    /// </summary>
    [Table("Sarpanch")]
    public partial class Sarpanch
    {
        [Key]
    	[Required] 
	    public virtual int id { get; set; }
        public virtual string constituency { get; set; }
        public virtual string District { get; set; }
        public virtual string Block { get; set; }
        public virtual string Panchayat { get; set; }
        public virtual string Name { get; set; }
        public virtual string Father_Husband_Name { get; set; }
        public virtual string mob_no { get; set; }
        public virtual string caste { get; set; }
        public virtual string gender { get; set; }
        public virtual string education { get; set; }
        public virtual string occupation { get; set; }
        public virtual DateTime? dob { get; set; }
        public virtual string approx_age { get; set; }
        public virtual string marital_status_id { get; set; }
        public virtual string cor_address1 { get; set; }
        public virtual string cor_address2 { get; set; }
        public virtual string cor_address3 { get; set; }
        public virtual string permanent_address1 { get; set; }
        public virtual string permanent_address2 { get; set; }
        public virtual string permanent_address3 { get; set; }
        public virtual string email_id { get; set; }
        public virtual string adhar_no { get; set; }

    }

    /// <summary>
    /// A class which represents the VILL_WORK table.
    /// </summary>
    [Table("VILL_WORK")]
    public partial class VILL_WORK
    {
        [Key]
    	[Required] 
	    public virtual int WORK_ID { get; set; }
        public virtual int? vill_id { get; set; }
        public virtual string VILL_GOOD_WORK { get; set; }
        public virtual string Vill_WORK_PROB { get; set; }
        public virtual string Remarks { get; set; }

    }

    /// <summary>
    /// A class which represents the VILL_PROBLEMS table.
    /// </summary>
    [Table("VILL_PROBLEMS")]
    public partial class VILL_PROBLEMS
    {
        [Key]
    	[Required] 
	    public virtual int PROBLEM_ID { get; set; }
        public virtual int? vill_id { get; set; }
        public virtual string Vill_WORK_PROB { get; set; }
        public virtual string Remarks { get; set; }
        public virtual string BLOCK { get; set; }

    }

    /// <summary>
    /// A class which represents the INFLUENCER table.
    /// </summary>
    [Table("INFLUENCER")]
    public partial class INFLUENCER
    {
        [Key]
    	[Required] 
	    public virtual int influencer_id { get; set; }
        public virtual int? vill_id { get; set; }
        public virtual string influencer_name { get; set; }
        public virtual string influencer_mobile { get; set; }
        public virtual string influencer_mobile2 { get; set; }
        public virtual string Party_Slant { get; set; }
        public virtual string Caste { get; set; }
        public virtual string Remarks { get; set; }

    }

    /// <summary>
    /// A class which represents the Vill_Connect table.
    /// </summary>
    [Table("Vill_Connect")]
    public partial class Vill_Connect
    {
        [Key]
    	[Required] 
	    public virtual int Connect_id { get; set; }
        public virtual string Connect_Name { get; set; }
        public virtual string Ward_Number { get; set; }
        public virtual string Connect_Mobile2 { get; set; }
        public virtual string Connect_Mobile { get; set; }
        public virtual string Connect_Caste { get; set; }
        public virtual int? vill_id { get; set; }
        public virtual string Remarks { get; set; }

    }

}
